In [1]:
from scipy.io import loadmat
import numpy as np

tut2 = loadmat('Tutorial_2.mat')
tut2.keys()

dict_keys(['__header__', '__version__', '__globals__', 'x1', 'x2', 'y', 'XXX'])

In [2]:
x1 = tut2['x1'].reshape(-1,1)
x2 = tut2['x2'].reshape(-1,1)
XXX = tut2['XXX'].reshape(-1,1)
y = tut2['y'].reshape(-1,1)
print(y.shape,x1.shape)

(2857, 1) (2857, 1)


In [3]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(x1, y)
r_2 = reg.score(x1,y)
print(f'x1 R^2 = {r_2}')
print(reg.coef_,reg.intercept_)

x1 R^2 = 0.5619495966956283
[[-774.38858515]] [1411.15540713]


In [4]:
# generate the model values
ny = reg.intercept_ + reg.coef_*x1

In [5]:
reg = LinearRegression().fit(x2, y)
r_2 = reg.score(x2,y)
print(f'x2 R^2 = {r_2}')
print(reg.coef_,reg.intercept_)

x2 R^2 = 0.43411881386055773
[[7.99276724]] [29.74801312]


In [6]:
xx = np.concatenate([x1,x2], axis=1)
reg_3 = LinearRegression().fit(xx, y)
r_3 = reg_3.score(xx,y)
print(f'R^2 = {r_3}')
print(reg_3.coef_,reg_3.intercept_)

R^2 = 0.5623518524818308
[[-7.38584331e+02  4.85773561e-01]] [1347.01168983]


In [7]:
reg_x = LinearRegression().fit(XXX, y)
r_x = reg_x.score(XXX,y)
print(f'R^2 = {r_x}')
print(reg_x.coef_,reg_x.intercept_)

R^2 = 0.5700403273478282
[[0.75413068]] [13.09182449]


In [8]:
# Pearson correlation
from scipy import stats

stats.pearsonr(XXX.reshape(-1), y.reshape(-1))

(0.7550101504932422, 0.0)

In [12]:
from numpy import linalg as LA
# MSE
print(1/(y.shape[0]) * LA.norm(XXX-y)**2)

140.0038333931914


In [10]:
xx_nl02 = xx**0.25
reg_nlx = LinearRegression().fit(xx_nl02, y)
r_nlx = reg_nlx.score(xx_nl02,y)
print(f'R^2 = {r_nlx}')
print(reg_nlx.coef_,reg_nlx.intercept_)

R^2 = 0.566329998712048
[[-3986.57213842    16.80405713]] [4619.60239446]


In [11]:
xx_exp = 10**xx
reg_elx = LinearRegression().fit(xx_exp, y)
r_elx = reg_elx.score(xx_exp,y)
print(f'R^2 = {r_elx}')
print(reg_elx.coef_,reg_elx.intercept_)

R^2 = 0.5876971213598876
[[-6.93767121e+00 -8.52118191e-07]] [448.25263159]
